# Generated by Django 4.2 on 2023-09-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corses', '0002_corse_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corse',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
